package me.saiskitchen.app

import android.content.Context
import android.content.Intent
import android.content.ContentValues
import android.graphics.BitmapFactory
import android.graphics.Canvas
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import android.graphics.Color
import android.graphics.Paint
import android.graphics.RectF
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import androidx.core.content.FileProvider
import java.io.File
import java.time.LocalDate

data class InvoiceSummary(
    val customer: Customer,
    val kind: InvoiceKind,
    val start: LocalDate,
    val end: LocalDate,
    val tiffins: List<TiffinEntry>,
    val orders: List<CateringOrder>,
    val settings: AppSettings,
    val previousBalance: Double = 0.0,
    val paidInPeriod: Double = 0.0,
) {
    val tiffinTotal get() = tiffins.sumOf { it.total }
    val cateringTotal get() = orders.sumOf { it.total }
    val grandTotal get() = when (kind) {
        InvoiceKind.Combined -> tiffinTotal + cateringTotal
        InvoiceKind.Tiffin -> tiffinTotal
        InvoiceKind.Catering -> cateringTotal
    }
}

object InvoicePdf {
    private const val W = 595
    private const val H = 842
    private const val M = 40f
    private val ORANGE = Color.rgb(255, 107, 53)
    private val TEXT = Color.rgb(45, 49, 66)
    private val MUTED = Color.rgb(107, 114, 128)
    private val LIGHT = Color.rgb(156, 163, 175)
    private val LINE = Color.rgb(229, 231, 235)
    private val MAROON = Color.rgb(160, 48, 26)

    private fun fit(text: String, p: Paint, maxW: Float): String {
        val n = p.breakText(text, true, maxW, null)
        return if (n < text.length) text.take(maxOf(n - 1, 1)) + "\u2026" else text
    }

    /** Draws one customer's invoice. Returns the last page number it used. */
    fun render(context: Context, s: InvoiceSummary, doc: PdfDocument, firstPage: Int, invoiceNo: String): Int {
        val cur = s.settings.currency
        val logo = runCatching { BitmapFactory.decodeResource(context.resources, R.drawable.invoice_logo) }.getOrNull()
        val today = Fmt.displayDate(LocalDate.now())
        var pageNo = firstPage
        var page = doc.startPage(PdfDocument.PageInfo.Builder(W, H, pageNo).create())
        var c = page.canvas

        fun footer() {
            c.drawRect(M, H - 70f, W - M, H - 69f, fill(LINE))
            c.drawText("Generated by ${s.settings.companyName} \u2022 $today", W / 2f, H - 48f, paint(9f, MUTED, align = Paint.Align.CENTER))
            c.drawText("For any queries, please contact ${s.settings.companyPhone}", W / 2f, H - 34f, paint(9f, MUTED, align = Paint.Align.CENTER))
        }
        fun newPage(): Float {
            footer(); doc.finishPage(page); pageNo++
            page = doc.startPage(PdfDocument.PageInfo.Builder(W, H, pageNo).create()); c = page.canvas
            c.drawText("${s.settings.companyName} - Invoice $invoiceNo - ${s.customer.name} (continued)", M, 44f, paint(9f, MUTED))
            c.drawRect(M, 52f, W - M, 53.5f, fill(ORANGE))
            return 84f
        }
        fun ensure(y: Float, need: Float): Float = if (y + need > H - 80f) newPage() else y

        // ---- header ----
        logo?.let { c.drawBitmap(it, null, RectF(M, 30f, M + 70f, 100f), Paint(Paint.FILTER_BITMAP_FLAG)) }
        val tx = if (logo != null) M + 82f else M
        c.drawText(s.settings.companyName, tx, 58f, paint(24f, ORANGE, true))
        c.drawText(s.settings.companyPhone, tx, 76f, paint(9.5f, MUTED))
        c.drawText(s.settings.companyAddress, tx, 90f, paint(9.5f, MUTED))
        c.drawText("INVOICE", W - M, 56f, paint(26f, TEXT, true, Paint.Align.RIGHT))
        c.drawText("Invoice #: $invoiceNo", W - M, 74f, paint(9.5f, MUTED, align = Paint.Align.RIGHT))
        c.drawText("Date: $today", W - M, 88f, paint(9.5f, MUTED, align = Paint.Align.RIGHT))
        c.drawText("Period: ${Fmt.displayDate(s.start)} - ${Fmt.displayDate(s.end)}", W - M, 102f, paint(9.5f, MUTED, align = Paint.Align.RIGHT))
        c.drawRect(M, 118f, W - M, 120f, fill(ORANGE))

        var y = 156f
        c.drawText("Bill To:", M + 6f, y, paint(11f, TEXT, true))
        c.drawText(s.customer.name, M + 6f, y + 18f, paint(11f, TEXT, true))
        if (s.customer.phone.isNotBlank()) c.drawText(s.customer.phone, M + 6f, y + 33f, paint(10f, MUTED))
        y += 76f

        fun sectionTitle(title: String, yy: Float): Float {
            c.drawText(title, M, yy, paint(15f, TEXT, true))
            c.drawRect(M, yy + 10f, W - M, yy + 11f, fill(LINE))
            return yy + 34f
        }
        fun summaryLine(label: String, value: String, yy: Float, bold: Boolean = false, color: Int = TEXT): Float {
            c.drawText(label, M + 6f, yy, paint(if (bold) 12f else 11f, color, bold))
            c.drawText(value, W - M - 10f, yy, paint(if (bold) 12f else 11f, color, true, Paint.Align.RIGHT))
            return yy + 22f
        }

        // ---- tiffin, day by day ----
        if (s.kind != InvoiceKind.Catering && s.tiffins.isNotEmpty()) {
            y = ensure(y, 120f)
            y = sectionTitle("Tiffin Services", y)
            fun tHeader(yy: Float): Float {
                val hp = paint(9f, LIGHT, true)
                c.drawText("Date", M + 6f, yy, hp)
                c.drawText("Noon Qty", 235f, yy, paint(9f, LIGHT, true, Paint.Align.RIGHT))
                c.drawText("Evening Qty", 312f, yy, paint(9f, LIGHT, true, Paint.Align.RIGHT))
                c.drawText("Unit Price", 392f, yy, paint(9f, LIGHT, true, Paint.Align.RIGHT))
                c.drawText("Delivery", 466f, yy, paint(9f, LIGHT, true, Paint.Align.RIGHT))
                c.drawText("Total", W - M - 10f, yy, paint(9f, LIGHT, true, Paint.Align.RIGHT))
                c.drawRect(M, yy + 9f, W - M, yy + 10f, fill(LINE))
                return yy + 30f
            }
            y = tHeader(y)
            for (t in s.tiffins) {
                if (y > H - 100f) { y = newPage(); y = tHeader(y) }
                c.drawText(Fmt.displayDate(t.date), M + 6f, y, paint(10.5f, MUTED))
                c.drawText(t.noonQty.clean(), 235f, y, paint(10.5f, TEXT, align = Paint.Align.RIGHT))
                c.drawText(t.eveningQty.clean(), 312f, y, paint(10.5f, TEXT, align = Paint.Align.RIGHT))
                c.drawText(Fmt.currency(t.unitPrice, cur), 392f, y, paint(10.5f, MUTED, align = Paint.Align.RIGHT))
                c.drawText(if (t.deliveryCharge > 0) Fmt.currency(t.deliveryCharge, cur) else "Free", 466f, y, paint(10.5f, MUTED, align = Paint.Align.RIGHT))
                c.drawText(Fmt.currency(t.total, cur), W - M - 10f, y, paint(10.5f, TEXT, true, Paint.Align.RIGHT))
                c.drawRect(M, y + 11f, W - M, y + 11.8f, fill(LINE))
                y += 31f
            }
            y = ensure(y + 6f, 90f)
            val meals = s.tiffins.sumOf { it.quantity }
            val food = s.tiffins.sumOf { it.quantity * it.unitPrice }
            val deliveryDays = s.tiffins.count { it.deliveryCharge > 0 }
            val delivery = s.tiffins.sumOf { it.deliveryCharge }
            y = summaryLine("Tiffins (${meals.clean()} meals)", Fmt.currency(food.cents(), cur), y)
            y = summaryLine("Delivery ($deliveryDays deliveries)", Fmt.currency(delivery.cents(), cur), y)
            y = summaryLine("Tiffin Subtotal:", Fmt.currency(s.tiffinTotal.cents(), cur), y, bold = true)
            y += 14f
        }

        // ---- catering, day by day ----
        if (s.kind != InvoiceKind.Tiffin && s.orders.isNotEmpty()) {
            y = ensure(y, 120f)
            y = sectionTitle("Catering Orders", y)
            fun cHeader(yy: Float): Float {
                c.drawText("Date", M + 6f, yy, paint(9f, LIGHT, true))
                c.drawText("Item", 130f, yy, paint(9f, LIGHT, true))
                c.drawText("Qty", 365f, yy, paint(9f, LIGHT, true, Paint.Align.RIGHT))
                c.drawText("Unit Price", 450f, yy, paint(9f, LIGHT, true, Paint.Align.RIGHT))
                c.drawText("Total", W - M - 10f, yy, paint(9f, LIGHT, true, Paint.Align.RIGHT))
                c.drawRect(M, yy + 9f, W - M, yy + 10f, fill(LINE))
                return yy + 30f
            }
            y = cHeader(y)
            val ip = paint(10.5f, TEXT)
            for (o in s.orders) {
                val lines = o.items.map { Triple(it.itemName, it.qty, it.unitPrice) } +
                    (if (o.deliveryCharge > 0) listOf(Triple("Delivery", 1.0, o.deliveryCharge)) else emptyList())
                lines.forEachIndexed { idx, (name, qty, unit) ->
                    if (y > H - 100f) { y = newPage(); y = cHeader(y) }
                    if (idx == 0) c.drawText(Fmt.displayDate(o.date), M + 6f, y, paint(10.5f, MUTED))
                    c.drawText(fit(name, ip, 215f), 130f, y, ip)
                    c.drawText(qty.clean(), 365f, y, paint(10.5f, TEXT, align = Paint.Align.RIGHT))
                    c.drawText(Fmt.currency(unit, cur), 450f, y, paint(10.5f, MUTED, align = Paint.Align.RIGHT))
                    c.drawText(Fmt.currency((qty * unit).cents(), cur), W - M - 10f, y, paint(10.5f, TEXT, true, Paint.Align.RIGHT))
                    c.drawRect(M, y + 11f, W - M, y + 11.8f, fill(LINE))
                    y += 29f
                }
            }
            y = ensure(y + 6f, 60f)
            y = summaryLine("Catering Subtotal:", Fmt.currency(s.cateringTotal.cents(), cur), y, bold = true)
            y += 14f
        }

        // ---- totals ----
        val hasBalance = Math.abs(s.previousBalance) > 0.004 || Math.abs(s.paidInPeriod) > 0.004
        y = ensure(y, if (hasBalance) 250f else 190f)
        val both = s.kind == InvoiceKind.Combined && s.tiffins.isNotEmpty() && s.orders.isNotEmpty()
        if (both) {
            y = summaryLine("Tiffin Subtotal:", Fmt.currency(s.tiffinTotal.cents(), cur), y)
            y = summaryLine("Catering Subtotal:", Fmt.currency(s.cateringTotal.cents(), cur), y)
        }
        y += 8f
        c.drawText("GRAND TOTAL:", M + 6f, y, paint(20f, ORANGE, true))
        c.drawText(Fmt.currency(s.grandTotal.cents(), cur), W - M - 10f, y, paint(20f, ORANGE, true, Paint.Align.RIGHT))
        y += 30f
        if (hasBalance) {
            if (Math.abs(s.previousBalance) > 0.004) y = summaryLine("Previous unpaid balance", Fmt.currency(s.previousBalance, cur), y)
            if (Math.abs(s.paidInPeriod) > 0.004) y = summaryLine("Payments received", "- " + Fmt.currency(s.paidInPeriod, cur), y)
            val due = (s.grandTotal + s.previousBalance - s.paidInPeriod).cents()
            c.drawRect(M, y - 8f, W - M, y - 7f, fill(LINE))
            y += 8f
            c.drawText("TOTAL DUE:", M + 6f, y, paint(16f, MAROON, true))
            c.drawText(Fmt.currency(due, cur), W - M - 10f, y, paint(16f, MAROON, true, Paint.Align.RIGHT))
            y += 30f
        }
        y += 16f
        c.drawText("Payment Details:", M + 6f, y, paint(10f, MAROON, true))
        c.drawText("BIC: ${PaymentDetails.BIC}", M + 6f, y + 15f, paint(10f, MAROON))
        c.drawText("IBAN: ${PaymentDetails.IBAN}", M + 6f, y + 30f, paint(10f, MAROON))
        c.drawText("Note: Thank you for your business! Payment is due within 7 days.", M + 6f, y + 56f, paint(10f, MAROON))
        footer()
        doc.finishPage(page)
        return pageNo
    }

    private fun invoiceNo() = "INV-" + System.currentTimeMillis()

    fun make(context: Context, s: InvoiceSummary): File {
        val doc = PdfDocument()
        render(context, s, doc, 1, invoiceNo())
        val dir = File(context.cacheDir, "invoices").apply { mkdirs() }
        val file = File(dir, "${s.customer.name.replace(" ", "_")}_Sai_Kitchen_Invoice_${LocalDate.now()}.pdf")
        file.outputStream().use { doc.writeTo(it) }
        doc.close()
        return file
    }

    /** Every invoice in one PDF, each customer starting on a new page. */
    fun makeCombined(context: Context, list: List<InvoiceSummary>, label: String): File {
        val doc = PdfDocument()
        var page = 0
        val base = System.currentTimeMillis()
        list.forEachIndexed { i, s -> page = render(context, s, doc, page + 1, "INV-${base + i}") }
        val dir = File(context.cacheDir, "invoices").apply { mkdirs() }
        val file = File(dir, "Sai_Kitchen_All_Invoices_${label.replace(" ", "_")}.pdf")
        file.outputStream().use { doc.writeTo(it) }
        doc.close()
        return file
    }

    /** One PDF per customer; returns the files. */
    fun makeEach(context: Context, list: List<InvoiceSummary>): List<File> {
        val base = System.currentTimeMillis()
        return list.mapIndexed { i, s ->
            val doc = PdfDocument()
            render(context, s, doc, 1, "INV-${base + i}")
            val dir = File(context.cacheDir, "invoices").apply { mkdirs() }
            val file = File(dir, "${s.customer.name.replace(" ", "_")}_Sai_Kitchen_Invoice_${s.start}_${s.end}.pdf")
            file.outputStream().use { doc.writeTo(it) }
            doc.close()
            file
        }
    }

    /** Copies the PDF into the phone's Downloads folder. */
    fun saveToDownloads(context: Context, file: File): Boolean = try {
        if (Build.VERSION.SDK_INT >= 29) {
            val values = ContentValues().apply {
                put(MediaStore.Downloads.DISPLAY_NAME, file.name)
                put(MediaStore.Downloads.MIME_TYPE, "application/pdf")
                put(MediaStore.Downloads.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS)
            }
            val uri = context.contentResolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, values)
            if (uri == null) false else {
                context.contentResolver.openOutputStream(uri)!!.use { out -> file.inputStream().use { it.copyTo(out) } }
                true
            }
        } else {
            val dir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).apply { mkdirs() }
            file.copyTo(File(dir, file.name), overwrite = true)
            true
        }
    } catch (e: Exception) { false }

    fun share(context: Context, file: File) {
        val uri = FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
        val send = Intent(Intent.ACTION_SEND).apply {
            type = "application/pdf"
            putExtra(Intent.EXTRA_STREAM, uri)
            putExtra(Intent.EXTRA_SUBJECT, file.nameWithoutExtension.replace('_', ' '))
            clipData = android.content.ClipData.newRawUri(file.name, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        val chooser = Intent.createChooser(send, "Share PDF").addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        // make sure every app in the share list is allowed to read the file (otherwise it opens as a blank PDF)
        context.packageManager.queryIntentActivities(send, 0).forEach {
            context.grantUriPermission(it.activityInfo.packageName, uri, Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(chooser)
    }

    private fun paint(size: Float, color: Int = TEXT, bold: Boolean = false, align: Paint.Align = Paint.Align.LEFT) =
        Paint(Paint.ANTI_ALIAS_FLAG).apply {
            textSize = size; this.color = color; textAlign = align
            typeface = if (bold) Typeface.DEFAULT_BOLD else Typeface.DEFAULT
        }

    private fun fill(color: Int) = Paint(Paint.ANTI_ALIAS_FLAG).apply { this.color = color }
}

/** Same bank details as the iPhone app's invoice. Edit here if they change. */
object PaymentDetails {
    const val BIC = "TRWIBEB1XXX"
    const val IBAN = "BE40 9676 8333 5963"
}
