package me.saiskitchen.app

import android.content.Context
import android.content.Intent
import android.content.ContentValues
import android.graphics.BitmapFactory
import android.graphics.Canvas
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import android.graphics.Color
import android.graphics.Paint
import android.graphics.RectF
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import androidx.core.content.FileProvider
import java.io.File
import java.time.LocalDate

data class InvoiceSummary(
    val customer: Customer,
    val kind: InvoiceKind,
    val start: LocalDate,
    val end: LocalDate,
    val tiffins: List<TiffinEntry>,
    val orders: List<CateringOrder>,
    val settings: AppSettings,
) {
    val tiffinTotal get() = tiffins.sumOf { it.total }
    val cateringTotal get() = orders.sumOf { it.total }
    val grandTotal get() = when (kind) {
        InvoiceKind.Combined -> tiffinTotal + cateringTotal
        InvoiceKind.Tiffin -> tiffinTotal
        InvoiceKind.Catering -> cateringTotal
    }
}

object InvoicePdf {
    private const val W = 595
    private const val H = 842
    private const val M = 40f
    private val ORANGE = Color.rgb(255, 107, 53)
    private val TEXT = Color.rgb(45, 49, 66)
    private val MUTED = Color.rgb(107, 114, 128)
    private val LIGHT = Color.rgb(156, 163, 175)
    private val LINE = Color.rgb(229, 231, 235)
    private val MAROON = Color.rgb(160, 48, 26)

    private data class Row(val item: String, val qty: Double, val unit: Double) {
        val total get() = (qty * unit).cents()
    }

    private fun rows(s: InvoiceSummary): List<Row> {
        val out = mutableListOf<Row>()
        val deliveries = mutableListOf<Double>()
        if (s.kind != InvoiceKind.Catering) {
            s.tiffins.groupBy { it.unitPrice }.forEach { (price, list) ->
                val q = list.sumOf { it.quantity }
                if (q > 0) out.add(Row("Tiffin Service", q, price))
            }
            s.tiffins.forEach { if (it.deliveryCharge > 0) deliveries.add(it.deliveryCharge) }
        }
        if (s.kind != InvoiceKind.Tiffin) {
            val merged = linkedMapOf<Pair<String, Double>, Double>()
            s.orders.forEach { o ->
                o.items.forEach { merged[Pair(it.itemName, it.unitPrice)] = (merged[Pair(it.itemName, it.unitPrice)] ?: 0.0) + it.qty }
                if (o.deliveryCharge > 0) deliveries.add(o.deliveryCharge)
            }
            merged.forEach { (k, q) -> out.add(Row(k.first, q, k.second)) }
        }
        deliveries.groupBy { it }.forEach { (charge, list) -> out.add(Row("Delivery", list.size.toDouble(), charge)) }
        return out
    }

    fun make(context: Context, s: InvoiceSummary): File {
        val doc = PdfDocument()
        val cur = s.settings.currency
        val logo = runCatching { BitmapFactory.decodeResource(context.resources, R.drawable.invoice_logo) }.getOrNull()
        val today = Fmt.displayDate(LocalDate.now())
        val invoiceNo = "INV-" + System.currentTimeMillis()
        val all = rows(s)
        val subtotal = all.sumOf { it.total }.cents()
        var pageNo = 1
        var page = doc.startPage(PdfDocument.PageInfo.Builder(W, H, pageNo).create())
        var c = page.canvas

        fun footer() {
            c.drawRect(M, H - 70f, W - M, H - 69f, fill(LINE))
            c.drawText("Generated by ${s.settings.companyName} \u2022 $today", W / 2f, H - 48f, paint(9f, MUTED, align = Paint.Align.CENTER))
            c.drawText("For any queries, please contact ${s.settings.companyPhone}", W / 2f, H - 34f, paint(9f, MUTED, align = Paint.Align.CENTER))
        }

        fun tableHeader(y: Float): Float {
            c.drawText("Item", M + 16f, y, paint(9f, LIGHT, true))
            c.drawText("Qty", 330f, y, paint(9f, LIGHT, true, Paint.Align.RIGHT))
            c.drawText("Unit Price", 430f, y, paint(9f, LIGHT, true, Paint.Align.RIGHT))
            c.drawText("Total", W - M - 16f, y, paint(9f, LIGHT, true, Paint.Align.RIGHT))
            c.drawRect(M, y + 10f, W - M, y + 11f, fill(LINE))
            return y + 34f
        }

        // header: logo + company on the left, INVOICE block on the right
        logo?.let { c.drawBitmap(it, null, RectF(M, 36f, M + 70f, 106f), Paint(Paint.FILTER_BITMAP_FLAG)) }
        val tx = if (logo != null) M + 86f else M
        c.drawText(s.settings.companyName, tx, 64f, paint(24f, ORANGE, true))
        c.drawText(s.settings.companyPhone, tx, 82f, paint(9.5f, MUTED))
        c.drawText(s.settings.companyAddress, tx, 96f, paint(9.5f, MUTED))
        c.drawText("INVOICE", W - M, 62f, paint(26f, TEXT, true, Paint.Align.RIGHT))
        c.drawText("Invoice #: $invoiceNo", W - M, 80f, paint(9.5f, MUTED, align = Paint.Align.RIGHT))
        c.drawText("Date: $today", W - M, 94f, paint(9.5f, MUTED, align = Paint.Align.RIGHT))
        c.drawRect(M, 124f, W - M, 126f, fill(ORANGE))

        var y = 162f
        c.drawText("Bill To:", M + 16f, y, paint(11f, TEXT, true))
        c.drawText(s.customer.name, M + 16f, y + 20f, paint(12f, MUTED, true))
        if (s.customer.phone.isNotBlank()) c.drawText(s.customer.phone, M + 16f, y + 36f, paint(10f, MUTED))
        y += 76f
        c.drawText("Order Details", M, y, paint(15f, TEXT, true))
        c.drawRect(M, y + 12f, W - M, y + 13f, fill(LINE))
        y = tableHeader(y + 38f)

        for (r in all) {
            if (y > H - 110f) {
                footer(); doc.finishPage(page); pageNo++
                page = doc.startPage(PdfDocument.PageInfo.Builder(W, H, pageNo).create()); c = page.canvas
                y = tableHeader(60f)
            }
            c.drawText(r.item, M + 16f, y, paint(11f, MUTED))
            c.drawText(r.qty.clean(), 330f, y, paint(11f, TEXT, align = Paint.Align.RIGHT))
            c.drawText(Fmt.currency(r.unit, cur), 430f, y, paint(11f, MUTED, align = Paint.Align.RIGHT))
            c.drawText(Fmt.currency(r.total, cur), W - M - 16f, y, paint(11f, TEXT, true, Paint.Align.RIGHT))
            c.drawRect(M, y + 11f, W - M, y + 11.8f, fill(LINE))
            y += 33f
        }
        c.drawText("Period: ${Fmt.displayDate(s.start)} - ${Fmt.displayDate(s.end)}", M + 16f, y - 12f, paint(9f, MUTED))
        y += 20f

        if (y > H - 270f) {
            footer(); doc.finishPage(page); pageNo++
            page = doc.startPage(PdfDocument.PageInfo.Builder(W, H, pageNo).create()); c = page.canvas
            y = 70f
        }
        c.drawText("Subtotal:", M + 16f, y, paint(12f, TEXT))
        c.drawText(Fmt.currency(subtotal, cur), W - M - 16f, y, paint(12f, TEXT, true, Paint.Align.RIGHT))
        y += 46f
        c.drawText("GRAND TOTAL:", M + 16f, y, paint(20f, ORANGE, true))
        c.drawText(Fmt.currency(subtotal, cur), W - M - 16f, y, paint(20f, ORANGE, true, Paint.Align.RIGHT))
        y += 56f

        c.drawText("Payment Details:", M + 16f, y, paint(10f, MAROON, true))
        c.drawText("BIC: ${PaymentDetails.BIC}", M + 16f, y + 15f, paint(10f, MAROON))
        c.drawText("IBAN: ${PaymentDetails.IBAN}", M + 16f, y + 30f, paint(10f, MAROON))
        c.drawText("Note: Thank you for your business! Payment is due within 7 days.", M + 16f, y + 56f, paint(10f, MAROON))
        footer()
        doc.finishPage(page)

        val dir = File(context.cacheDir, "invoices").apply { mkdirs() }
        val name = "${s.customer.name.replace(" ", "_")}_Sai_Kitchen_Invoice_${LocalDate.now()}.pdf"
        val file = File(dir, name)
        file.outputStream().use { doc.writeTo(it) }
        doc.close()
        return file
    }

    /** Copies the PDF into the phone's Downloads folder. */
    fun saveToDownloads(context: Context, file: File): Boolean = try {
        if (Build.VERSION.SDK_INT >= 29) {
            val values = ContentValues().apply {
                put(MediaStore.Downloads.DISPLAY_NAME, file.name)
                put(MediaStore.Downloads.MIME_TYPE, "application/pdf")
                put(MediaStore.Downloads.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS)
            }
            val uri = context.contentResolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, values)
            if (uri == null) false else {
                context.contentResolver.openOutputStream(uri)!!.use { out -> file.inputStream().use { it.copyTo(out) } }
                true
            }
        } else {
            val dir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).apply { mkdirs() }
            file.copyTo(File(dir, file.name), overwrite = true)
            true
        }
    } catch (e: Exception) { false }

    fun share(context: Context, file: File) {
        val uri = FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
        val send = Intent(Intent.ACTION_SEND).apply {
            type = "application/pdf"
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(send, "Share PDF").addFlags(Intent.FLAG_ACTIVITY_NEW_TASK))
    }

    private fun paint(size: Float, color: Int = TEXT, bold: Boolean = false, align: Paint.Align = Paint.Align.LEFT) =
        Paint(Paint.ANTI_ALIAS_FLAG).apply {
            textSize = size; this.color = color; textAlign = align
            typeface = if (bold) Typeface.DEFAULT_BOLD else Typeface.DEFAULT
        }

    private fun fill(color: Int) = Paint(Paint.ANTI_ALIAS_FLAG).apply { this.color = color }
}

/** Same bank details as the iPhone app's invoice. Edit here if they change. */
object PaymentDetails {
    const val BIC = "TRWIBEB1XXX"
    const val IBAN = "BE40 9676 8333 5963"
}
