package me.saiskitchen.app

import android.content.Context
import android.graphics.BitmapFactory
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.RectF
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import java.io.File
import java.time.LocalDate

/** One customer line of the monthly outstanding report. balance = unpaid brought forward + billed this period - paid. */
data class OutstandingRow(
    val customerId: String, val name: String, val phone: String,
    val tiffin: Double, val catering: Double, val previous: Double, val paid: Double,
) {
    val billed get() = tiffin + catering
    val balance get() = (previous + tiffin + catering - paid).cents()
}

/** A4 outstanding report: Sai's Kitchen header, total outstanding amount, per-customer table. */
object ReportPdf {
    private const val W = 595
    private const val H = 842
    private const val M = 40f
    private val ORANGE = Color.rgb(255, 107, 53)
    private val TEXT = Color.rgb(45, 49, 66)
    private val MUTED = Color.rgb(107, 114, 128)
    private val LIGHT = Color.rgb(156, 163, 175)
    private val LINE = Color.rgb(229, 231, 235)
    private val MAROON = Color.rgb(160, 48, 26)

    private fun paint(size: Float, color: Int = TEXT, bold: Boolean = false, align: Paint.Align = Paint.Align.LEFT) =
        Paint(Paint.ANTI_ALIAS_FLAG).apply {
            textSize = size; this.color = color; textAlign = align
            typeface = if (bold) Typeface.DEFAULT_BOLD else Typeface.DEFAULT
        }
    private fun fill(color: Int) = Paint(Paint.ANTI_ALIAS_FLAG).apply { this.color = color }

    fun outstanding(context: Context, monthLabel: String, rows: List<OutstandingRow>, settings: AppSettings): File {
        val doc = PdfDocument()
        val cur = settings.currency
        val logo = runCatching { BitmapFactory.decodeResource(context.resources, R.drawable.invoice_logo) }.getOrNull()
        val today = Fmt.displayDate(LocalDate.now())
        val totalOutstanding = rows.sumOf { it.balance }.cents()
        var pageNo = 1
        var page = doc.startPage(PdfDocument.PageInfo.Builder(W, H, pageNo).create())
        var c: Canvas = page.canvas

        fun money(v: Double) = Fmt.currency(v, cur)
        fun dash(v: Double) = if (Math.abs(v) < 0.004) "-" else money(v)

        fun footer() {
            c.drawRect(M, H - 70f, W - M, H - 69f, fill(LINE))
            c.drawText("Generated by ${settings.companyName}", W / 2f, H - 48f, paint(9f, MUTED, align = Paint.Align.CENTER))
            c.drawText("For any queries, please contact ${settings.companyPhone}", W / 2f, H - 34f, paint(9f, MUTED, align = Paint.Align.CENTER))
        }
        fun tableHeader(y: Float): Float {
            val h = { a: Paint.Align -> paint(8.5f, LIGHT, true, a) }
            c.drawText("Sr No.", M + 6f, y, h(Paint.Align.LEFT))
            c.drawText("Customer Name", 92f, y, h(Paint.Align.LEFT))
            c.drawText("Tiffin", 335f, y, h(Paint.Align.RIGHT))
            c.drawText("Catering", 392f, y, h(Paint.Align.RIGHT))
            c.drawText("Previous", 450f, y, h(Paint.Align.RIGHT))
            c.drawText("Paid", 500f, y, h(Paint.Align.RIGHT))
            c.drawText("Balance", W - M - 6f, y, h(Paint.Align.RIGHT))
            c.drawRect(M, y + 9f, W - M, y + 10f, fill(LINE))
            return y + 30f
        }

        // header
        logo?.let { c.drawBitmap(it, null, RectF(M, 30f, M + 70f, 100f), Paint(Paint.FILTER_BITMAP_FLAG)) }
        val tx = if (logo != null) M + 82f else M
        c.drawText(settings.companyName, tx, 58f, paint(24f, ORANGE, true))
        c.drawText(settings.companyPhone, tx, 76f, paint(9.5f, MUTED))
        c.drawText(settings.companyAddress, tx, 90f, paint(9.5f, MUTED))
        c.drawText("OUTSTANDING", W - M, 50f, paint(20f, TEXT, true, Paint.Align.RIGHT))
        c.drawText("REPORT", W - M, 72f, paint(20f, TEXT, true, Paint.Align.RIGHT))
        c.drawText("Period: $monthLabel", W - M, 88f, paint(9.5f, MUTED, align = Paint.Align.RIGHT))
        c.drawText("Generated: $today", W - M, 101f, paint(9.5f, MUTED, align = Paint.Align.RIGHT))
        c.drawText("Total Customers: ${rows.size}", W - M, 114f, paint(9.5f, MUTED, align = Paint.Align.RIGHT))
        c.drawRect(M, 126f, W - M, 128f, fill(ORANGE))

        // big total
        c.drawText("Total Outstanding Amount", W / 2f, 168f, paint(13f, MAROON, true, Paint.Align.CENTER))
        c.drawText(money(totalOutstanding), W / 2f, 202f, paint(30f, ORANGE, true, Paint.Align.CENTER))
        val billed = rows.sumOf { it.billed }
        val paidSum = rows.sumOf { it.paid }
        val prev = rows.sumOf { it.previous }
        c.drawText("Billed this period ${money(billed.cents())}  •  Unpaid from before ${money(prev.cents())}  •  Payments received ${money(paidSum.cents())}",
            W / 2f, 222f, paint(9f, MUTED, align = Paint.Align.CENTER))

        var y = tableHeader(262f)
        rows.forEachIndexed { i, r ->
            if (y > H - 100f) {
                footer(); doc.finishPage(page); pageNo++
                page = doc.startPage(PdfDocument.PageInfo.Builder(W, H, pageNo).create()); c = page.canvas
                c.drawText("${settings.companyName} - Outstanding Report - $monthLabel (continued)", M, 44f, paint(9f, MUTED))
                c.drawRect(M, 52f, W - M, 53.5f, fill(ORANGE))
                y = tableHeader(84f)
            }
            val np = paint(10.5f, TEXT)
            c.drawText("${i + 1}", M + 12f, y, paint(10f, MUTED, align = Paint.Align.CENTER))
            val nameShown = np.breakText(r.name, true, 170f, null).let { n -> if (n < r.name.length) r.name.take(maxOf(n - 1, 1)) + "…" else r.name }
            c.drawText(nameShown, 92f, y, np)
            c.drawText(money(r.tiffin), 335f, y, paint(10f, MUTED, align = Paint.Align.RIGHT))
            c.drawText(money(r.catering), 392f, y, paint(10f, MUTED, align = Paint.Align.RIGHT))
            c.drawText(dash(r.previous), 450f, y, paint(10f, MUTED, align = Paint.Align.RIGHT))
            c.drawText(dash(r.paid), 500f, y, paint(10f, MUTED, align = Paint.Align.RIGHT))
            c.drawText(money(r.balance), W - M - 6f, y, paint(10.5f, TEXT, true, Paint.Align.RIGHT))
            c.drawRect(M, y + 11f, W - M, y + 11.8f, fill(LINE))
            y += 29f
        }
        if (rows.isEmpty()) c.drawText("Nothing outstanding for this period.", M + 6f, y, paint(12f, MUTED))
        else {
            if (y > H - 100f) {
                footer(); doc.finishPage(page); pageNo++
                page = doc.startPage(PdfDocument.PageInfo.Builder(W, H, pageNo).create()); c = page.canvas
                y = 84f
            }
            y += 4f
            c.drawText("TOTAL", 92f, y, paint(12f, ORANGE, true))
            c.drawText(money(rows.sumOf { it.tiffin }.cents()), 335f, y, paint(10f, TEXT, true, Paint.Align.RIGHT))
            c.drawText(money(rows.sumOf { it.catering }.cents()), 392f, y, paint(10f, TEXT, true, Paint.Align.RIGHT))
            c.drawText(dash(prev.cents()), 450f, y, paint(10f, TEXT, true, Paint.Align.RIGHT))
            c.drawText(dash(paidSum.cents()), 500f, y, paint(10f, TEXT, true, Paint.Align.RIGHT))
            c.drawText(money(totalOutstanding), W - M - 6f, y, paint(12f, ORANGE, true, Paint.Align.RIGHT))
            y += 40f
            c.drawText("Payment Details:", M + 6f, y, paint(10f, MAROON, true))
            c.drawText("BIC: ${PaymentDetails.BIC}   IBAN: ${PaymentDetails.IBAN}", M + 6f, y + 15f, paint(10f, MAROON))
        }
        footer()
        doc.finishPage(page)

        val dir = File(context.cacheDir, "invoices").apply { mkdirs() }
        val file = File(dir, "Outstanding_Report_${monthLabel.replace(" ", "_")}.pdf")
        file.outputStream().use { doc.writeTo(it) }
        doc.close()
        return file
    }

    fun share(context: Context, file: File) = InvoicePdf.share(context, file)
}
