import Foundation
import UIKit

struct InvoiceSummary {
    let customer: Customer
    let kind: InvoiceKind
    let startDate: Date
    let endDate: Date
    let tiffins: [TiffinEntry]
    let cateringOrders: [CateringOrder]
    let settings: AppSettings

    var tiffinTotal: Double { tiffins.reduce(0) { $0 + $1.total } }
    var cateringTotal: Double { cateringOrders.reduce(0) { $0 + $1.total } }
    var grandTotal: Double {
        switch kind {
        case .combined: return tiffinTotal + cateringTotal
        case .tiffin: return tiffinTotal
        case .catering: return cateringTotal
        }
    }
}

@MainActor
enum InvoicePDFGenerator {
    private struct Row {
        let item: String
        let qty: Double
        let unit: Double
        var total: Double { (qty * unit).roundedToCents }
    }

    private static func rows(_ s: InvoiceSummary) -> [Row] {
        var out: [Row] = []
        var deliveries: [Double] = []
        if s.kind == .combined || s.kind == .tiffin {
            let groups = Dictionary(grouping: s.tiffins, by: { $0.unitPrice })
            for price in groups.keys.sorted() {
                let q = groups[price]!.reduce(0) { $0 + $1.quantity }
                if q > 0 { out.append(Row(item: "Tiffin Service", qty: q, unit: price)) }
            }
            deliveries += s.tiffins.filter { $0.deliveryCharge > 0 }.map { $0.deliveryCharge }
        }
        if s.kind == .combined || s.kind == .catering {
            var order: [String] = []
            var qtys: [String: Double] = [:]
            var info: [String: (String, Double)] = [:]
            for o in s.cateringOrders {
                for it in o.items {
                    let key = "\(it.itemName)|\(it.unitPrice)"
                    if qtys[key] == nil { order.append(key); info[key] = (it.itemName, it.unitPrice) }
                    qtys[key, default: 0] += it.qty
                }
                if o.deliveryCharge > 0 { deliveries.append(o.deliveryCharge) }
            }
            for key in order { out.append(Row(item: info[key]!.0, qty: qtys[key] ?? 0, unit: info[key]!.1)) }
        }
        let dg = Dictionary(grouping: deliveries, by: { $0 })
        for charge in dg.keys.sorted() { out.append(Row(item: "Delivery", qty: Double(dg[charge]!.count), unit: charge)) }
        return out
    }

    static func makePDF(summary: InvoiceSummary) throws -> URL {
        let page = CGRect(x: 0, y: 0, width: 595, height: 842)
        let renderer = UIGraphicsPDFRenderer(bounds: page)
        let fileName = "\(summary.customer.name.replacingOccurrences(of: " ", with: "_"))_Sai_Kitchen_Invoice_\(AppFormatters.isoDate(Date())).pdf"
        let url = FileManager.default.temporaryDirectory.appendingPathComponent(fileName)

        let orange = UIColor(red: 1.0, green: 0.42, blue: 0.21, alpha: 1)
        let text = UIColor(red: 0.18, green: 0.19, blue: 0.26, alpha: 1)
        let muted = UIColor(red: 0.42, green: 0.45, blue: 0.50, alpha: 1)
        let light = UIColor(red: 0.61, green: 0.64, blue: 0.69, alpha: 1)
        let line = UIColor(red: 0.9, green: 0.91, blue: 0.92, alpha: 1)
        let maroon = UIColor(red: 0.63, green: 0.19, blue: 0.10, alpha: 1)
        let m: CGFloat = 40
        let cur = summary.settings.currency
        let today = AppFormatters.displayDate(Date())
        let invoiceNo = "INV-\(Int(Date().timeIntervalSince1970 * 1000))"
        let all = rows(summary)
        let subtotal = all.reduce(0) { $0 + $1.total }.roundedToCents
        let logo = UIImage(named: "InvoiceLogo")

        func draw(_ str: String, x: CGFloat, y: CGFloat, w: CGFloat = 400, size: CGFloat, bold: Bool = false, color: UIColor = text, align: NSTextAlignment = .left) {
            let p = NSMutableParagraphStyle()
            p.alignment = align
            let attrs: [NSAttributedString.Key: Any] = [
                .font: bold ? UIFont.boldSystemFont(ofSize: size) : UIFont.systemFont(ofSize: size),
                .foregroundColor: color, .paragraphStyle: p,
            ]
            (str as NSString).draw(in: CGRect(x: x, y: y - size, width: w, height: size + 8), withAttributes: attrs)
        }
        func rule(_ ctx: CGContext, y: CGFloat, h: CGFloat = 1, color: UIColor) {
            color.setFill()
            ctx.fill(CGRect(x: m, y: y, width: page.width - 2 * m, height: h))
        }
        func footer(_ ctx: CGContext) {
            rule(ctx, y: page.height - 70, color: line)
            draw("Generated by \(summary.settings.companyName) \u{2022} \(today)", x: 0, y: page.height - 40, w: page.width, size: 9, color: muted, align: .center)
            draw("For any queries, please contact \(summary.settings.companyPhone)", x: 0, y: page.height - 26, w: page.width, size: 9, color: muted, align: .center)
        }
        func tableHeader(_ ctx: CGContext, y: CGFloat) -> CGFloat {
            draw("Item", x: m + 16, y: y, size: 9, bold: true, color: light)
            draw("Qty", x: 230, y: y, w: 100, size: 9, bold: true, color: light, align: .right)
            draw("Unit Price", x: 330, y: y, w: 100, size: 9, bold: true, color: light, align: .right)
            draw("Total", x: page.width - m - 116, y: y, w: 100, size: 9, bold: true, color: light, align: .right)
            rule(ctx, y: y + 10, color: line)
            return y + 34
        }

        try renderer.writePDF(to: url) { context in
            context.beginPage()
            let ctx = context.cgContext
            logo?.draw(in: CGRect(x: m, y: 36, width: 70, height: 70))
            let tx = logo != nil ? m + 86 : m
            draw(summary.settings.companyName, x: tx, y: 64, w: 260, size: 24, bold: true, color: orange)
            draw(summary.settings.companyPhone, x: tx, y: 82, w: 300, size: 9.5, color: muted)
            draw(summary.settings.companyAddress, x: tx, y: 96, w: 330, size: 9.5, color: muted)
            draw("INVOICE", x: page.width - m - 200, y: 62, w: 200, size: 26, bold: true, align: .right)
            draw("Invoice #: \(invoiceNo)", x: page.width - m - 240, y: 80, w: 240, size: 9.5, color: muted, align: .right)
            draw("Date: \(today)", x: page.width - m - 240, y: 94, w: 240, size: 9.5, color: muted, align: .right)
            rule(ctx, y: 124, h: 2, color: orange)

            var y: CGFloat = 162
            draw("Bill To:", x: m + 16, y: y, size: 11, bold: true)
            draw(summary.customer.name, x: m + 16, y: y + 20, w: 300, size: 12, bold: true, color: muted)
            if !summary.customer.phone.isEmpty { draw(summary.customer.phone, x: m + 16, y: y + 36, w: 300, size: 10, color: muted) }
            y += 76
            draw("Order Details", x: m, y: y, size: 15, bold: true)
            rule(ctx, y: y + 12, color: line)
            y = tableHeader(ctx, y: y + 38)

            for r in all {
                if y > page.height - 110 {
                    footer(ctx)
                    context.beginPage()
                    y = tableHeader(ctx, y: 60)
                }
                draw(r.item, x: m + 16, y: y, w: 220, size: 11, color: muted)
                draw(r.qty.clean, x: 230, y: y, w: 100, size: 11, align: .right)
                draw(AppFormatters.currency(r.unit, code: cur), x: 330, y: y, w: 100, size: 11, color: muted, align: .right)
                draw(AppFormatters.currency(r.total, code: cur), x: page.width - m - 116, y: y, w: 100, size: 11, bold: true, align: .right)
                rule(ctx, y: y + 11, h: 0.8, color: line)
                y += 33
            }
            draw("Period: \(AppFormatters.displayDate(summary.startDate)) - \(AppFormatters.displayDate(summary.endDate))", x: m + 16, y: y - 12, size: 9, color: muted)
            y += 20

            if y > page.height - 270 {
                footer(ctx)
                context.beginPage()
                y = 70
            }
            draw("Subtotal:", x: m + 16, y: y, size: 12)
            draw(AppFormatters.currency(subtotal, code: cur), x: page.width - m - 216, y: y, w: 200, size: 12, bold: true, align: .right)
            y += 46
            draw("GRAND TOTAL:", x: m + 16, y: y, size: 20, bold: true, color: orange)
            draw(AppFormatters.currency(subtotal, code: cur), x: page.width - m - 216, y: y, w: 200, size: 20, bold: true, color: orange, align: .right)
            y += 56

            draw("Payment Details:", x: m + 16, y: y, size: 10, bold: true, color: maroon)
            draw("BIC: TRWIBEB1XXX", x: m + 16, y: y + 15, size: 10, color: maroon)
            draw("IBAN: BE40 9676 8333 5963", x: m + 16, y: y + 30, size: 10, color: maroon)
            draw("Note: Thank you for your business! Payment is due within 7 days.", x: m + 16, y: y + 56, w: 500, size: 10, color: maroon)
            footer(ctx)
        }
        return url
    }
}
