import UIKit

/// One customer line of the monthly outstanding report. balance = unpaid brought forward + billed this period - paid.
struct OutstandingRow {
    var customerId: String
    var name: String
    var phone: String
    var tiffin: Double
    var catering: Double
    var previous: Double
    var paid: Double
    var billed: Double { tiffin + catering }
    var balance: Double { (previous + tiffin + catering - paid).roundedToCents }
}

@MainActor
enum OutstandingPDF {
    static func make(monthLabel: String, rows: [OutstandingRow], settings: AppSettings) throws -> URL {
        let page = CGRect(x: 0, y: 0, width: 595, height: 842)
        let m: CGFloat = 40
        let orange = UIColor(red: 1.0, green: 0.42, blue: 0.21, alpha: 1)
        let text = UIColor(red: 0.18, green: 0.19, blue: 0.26, alpha: 1)
        let muted = UIColor(red: 0.42, green: 0.45, blue: 0.5, alpha: 1)
        let light = UIColor(red: 0.61, green: 0.64, blue: 0.69, alpha: 1)
        let line = UIColor(red: 0.9, green: 0.91, blue: 0.92, alpha: 1)
        let maroon = UIColor(red: 0.63, green: 0.19, blue: 0.10, alpha: 1)
        let url = FileManager.default.temporaryDirectory.appendingPathComponent("Outstanding_Report_\(monthLabel.replacingOccurrences(of: " ", with: "_")).pdf")
        let cur = settings.currency
        let today = AppFormatters.displayDate(Date())
        let logo = UIImage(named: "InvoiceLogo")
        func money(_ v: Double) -> String { AppFormatters.currency(v, code: cur) }
        func dash(_ v: Double) -> String { abs(v) < 0.004 ? "-" : money(v) }

        func draw(_ s: String, x: CGFloat, y: CGFloat, w: CGFloat = 400, size: CGFloat, bold: Bool = false, color: UIColor = text, align: NSTextAlignment = .left) {
            let p = NSMutableParagraphStyle()
            p.alignment = align
            p.lineBreakMode = .byTruncatingTail
            let attrs: [NSAttributedString.Key: Any] = [
                .font: bold ? UIFont.boldSystemFont(ofSize: size) : UIFont.systemFont(ofSize: size),
                .foregroundColor: color, .paragraphStyle: p,
            ]
            (s as NSString).draw(in: CGRect(x: x, y: y - size, width: w, height: size + 8), withAttributes: attrs)
        }
        func right(_ s: String, _ edge: CGFloat, _ y: CGFloat, size: CGFloat, bold: Bool = false, color: UIColor = text) {
            draw(s, x: edge - 120, y: y, w: 120, size: size, bold: bold, color: color, align: .right)
        }
        func rule(_ ctx: CGContext, y: CGFloat, h: CGFloat = 1, color: UIColor) {
            color.setFill()
            ctx.fill(CGRect(x: m, y: y, width: page.width - 2 * m, height: h))
        }
        func footer(_ ctx: CGContext) {
            rule(ctx, y: page.height - 70, color: line)
            draw("Generated by \(settings.companyName)", x: 0, y: page.height - 44, w: page.width, size: 9, color: muted, align: .center)
            draw("For any queries, please contact \(settings.companyPhone)", x: 0, y: page.height - 30, w: page.width, size: 9, color: muted, align: .center)
        }
        func tableHeader(_ ctx: CGContext, _ y: CGFloat) -> CGFloat {
            draw("Sr No.", x: m + 6, y: y, w: 50, size: 8.5, bold: true, color: light)
            draw("Customer Name", x: 92, y: y, w: 170, size: 8.5, bold: true, color: light)
            right("Tiffin", 335, y, size: 8.5, bold: true, color: light)
            right("Catering", 392, y, size: 8.5, bold: true, color: light)
            right("Previous", 450, y, size: 8.5, bold: true, color: light)
            right("Paid", 500, y, size: 8.5, bold: true, color: light)
            right("Balance", page.width - m - 6, y, size: 8.5, bold: true, color: light)
            rule(ctx, y: y + 9, color: line)
            return y + 30
        }

        let totalOutstanding = rows.reduce(0) { $0 + $1.balance }.roundedToCents
        let billed = rows.reduce(0) { $0 + $1.billed }
        let paidSum = rows.reduce(0) { $0 + $1.paid }
        let prev = rows.reduce(0) { $0 + $1.previous }

        try UIGraphicsPDFRenderer(bounds: page).writePDF(to: url) { context in
            context.beginPage()
            var ctx = context.cgContext
            logo?.draw(in: CGRect(x: m, y: 30, width: 70, height: 70))
            let tx = logo != nil ? m + 82 : m
            draw(settings.companyName, x: tx, y: 58, w: 260, size: 24, bold: true, color: orange)
            draw(settings.companyPhone, x: tx, y: 76, w: 300, size: 9.5, color: muted)
            draw(settings.companyAddress, x: tx, y: 90, w: 330, size: 9.5, color: muted)
            right("OUTSTANDING", page.width - m, 50, size: 20, bold: true)
            right("REPORT", page.width - m, 72, size: 20, bold: true)
            right("Period: \(monthLabel)", page.width - m, 88, size: 9.5, color: muted)
            right("Generated: \(today)", page.width - m, 101, size: 9.5, color: muted)
            right("Total Customers: \(rows.count)", page.width - m, 114, size: 9.5, color: muted)
            rule(ctx, y: 126, h: 2, color: orange)

            draw("Total Outstanding Amount", x: 0, y: 168, w: page.width, size: 13, bold: true, color: maroon, align: .center)
            draw(money(totalOutstanding), x: 0, y: 202, w: page.width, size: 30, bold: true, color: orange, align: .center)
            draw("Billed this period \(money(billed.roundedToCents))  \u{2022}  Unpaid from before \(money(prev.roundedToCents))  \u{2022}  Payments received \(money(paidSum.roundedToCents))",
                 x: 0, y: 222, w: page.width, size: 9, color: muted, align: .center)

            var y = tableHeader(ctx, 262)
            for (i, r) in rows.enumerated() {
                if y > page.height - 100 {
                    footer(ctx)
                    context.beginPage()
                    ctx = context.cgContext
                    draw("\(settings.companyName) - Outstanding Report - \(monthLabel) (continued)", x: m, y: 44, w: 500, size: 9, color: muted)
                    rule(ctx, y: 52, h: 1.5, color: orange)
                    y = tableHeader(ctx, 84)
                }
                draw("\(i + 1)", x: m + 6, y: y, w: 30, size: 10, color: muted)
                draw(r.name, x: 92, y: y, w: 170, size: 10.5)
                right(money(r.tiffin), 335, y, size: 10, color: muted)
                right(money(r.catering), 392, y, size: 10, color: muted)
                right(dash(r.previous), 450, y, size: 10, color: muted)
                right(dash(r.paid), 500, y, size: 10, color: muted)
                right(money(r.balance), page.width - m - 6, y, size: 10.5, bold: true)
                rule(ctx, y: y + 11, h: 0.8, color: line)
                y += 29
            }
            if rows.isEmpty {
                draw("Nothing outstanding for this period.", x: m + 6, y: y, w: 400, size: 12, color: muted)
            } else {
                if y > page.height - 100 {
                    footer(ctx)
                    context.beginPage()
                    ctx = context.cgContext
                    y = 84
                }
                y += 4
                draw("TOTAL", x: 92, y: y, w: 100, size: 12, bold: true, color: orange)
                right(money(rows.reduce(0) { $0 + $1.tiffin }.roundedToCents), 335, y, size: 10, bold: true)
                right(money(rows.reduce(0) { $0 + $1.catering }.roundedToCents), 392, y, size: 10, bold: true)
                right(dash(prev.roundedToCents), 450, y, size: 10, bold: true)
                right(dash(paidSum.roundedToCents), 500, y, size: 10, bold: true)
                right(money(totalOutstanding), page.width - m - 6, y, size: 12, bold: true, color: orange)
                y += 40
                draw("Payment Details:", x: m + 6, y: y, w: 300, size: 10, bold: true, color: maroon)
                draw("BIC: TRWIBEB1XXX   IBAN: BE40 9676 8333 5963", x: m + 6, y: y + 15, w: 400, size: 10, color: maroon)
            }
            footer(ctx)
        }
        return url
    }
}
